apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-catalogue-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: service-catalogue-operator
  template:
    metadata:
      labels:
        application: service-catalogue-operator
    spec:
      serviceAccountName: service-catalogue-operator
      containers:
      - name: service-catalogue
        image: {{IMAGE_REGISTRY}}/{{IMAGE_REPOSITORY}}:{{IMAGE_TAG}}
        imagePullPolicy: Always
        env:
        - name: REPO_NAME
          value: {{REPO_NAME}}
        - name: REPO_UPDATE_INTERVAL
          value: {{REPO_UPDATE_INTERVAL}}
        - name: REPO_USERNAME
          value: {{REPO_USERNAME}}
        - name: REPO_PASSWORD
          value: {{REPO_PASSWORD}}
        - name: REPO_ADDRESS
          value: {{REPO_ADDRESS}}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
